- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install rsyslog
      yum:
        name: rsyslog
        state: latest

    - name: Start rsyslog Service
      service:
        name: rsyslog
        state: started
        enabled: yes

    - name: Start firewalld Service
      service:
        name: firewalld
        state: started

    - name: Install httpd
      yum:
        name: httpd
        state: latest
      when: "'apache' in group_names"

    - name: Install httpd-tools
      yum:
        name: httpd-tools
        state: latest
      when: "'apache' in group_names"

    - name: Start httpd Service
      service:
        name: httpd
        state: started
      when: "'apache' in group_names"

    - name: Enable httpd Service
      service:
        name: httpd
        enabled: yes
      when: "'apache' in group_names"

    - name: Start firewalld Service
      service:
        name: firewalld
        state: started

    - name: Add Service http to public zone firewalld
      firewalld:
        service: http
        zone: public
        permanent: yes
        state: enabled
      when: "'web' in group_names"

    - name: Add Service https to public zone firewalld
      firewalld:
        service: https
        zone: public
        permanent: yes
        state: enabled
      when: "'web' in group_names"

    - name: Restart firewalld Service
      service:
        name: firewalld
        state: restarted
      when: "'web' in group_names"

    ###########Config syslog###########

    - name: Open firewall 514tcp and 514udp
      firewalld:
        port: "{{ item }}"
        zone: public
        permanent: yes
        state: enabled
      loop:
        - "514/udp"
        - "514/tcp"

    - name: Restart firewalld Service
      service:
        name: firewalld
        state: restarted

    - name: Uncomment in rsyslog.conf
      blockinfile:
        path: /etc/rsyslog.conf
        block: |
          module(load="imudp")
          input(type="imudp" port="514")
          module(load="imtcp")
          input(type="imtcp" port="514")
        backup: yes
      when: "'logServer' in group_names"

    - name: Add CustomLog
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        block: |
          CustomLog "| /bin/sh -c '/usr/bin/tee -a /var/log/httpd/httpd-access.log | /usr/bin/logger -thttpd -plocal6.info'" combined
        backup: yes
      when: "'apache' in group_names"

    - name: Add CustomLog
      blockinfile:
        path: /etc/rsyslog.conf
        block: |
          action(type="omfwd" Target="192.168.147.11" Port="514" Protocol="udp")
          action(type="omfwd" Target="192.168.147.11" Port="514" Protocol="tcp")
        backup: yes
      when: "'logServer' not in group_names"

    - name: Restarte httpd Service
      service:
        name: httpd
        state: restarted
      when: "'apache' in group_names"

    - name: Restart rsyslog Service
      service:
        name: rsyslog
        state: restarted
