---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: install Bind
    yum:
      name: bind
      state: latest

  - name: install Bindutil
    yum:
      name: bind-utils
      state: latest


    
  # - name: Check name server
  #   shell: cat /etc/resolv.conf | grep nameserver
  #   register: myoutput
  # - debug: msg="{{ myoutput.stdout }}"

  # - name: Check hostname
  #   shell: hostname
  #   register: myhost
  # - debug: msg="{{ myhost.stdout }}"
