- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Start mariadb Service
      yum:
        name: httpd
        state: removed
    # - name: Allow NTP client access from local network.
    #   lineinfile:
    #     path: /etc/rsyslog.conf
    #     regexp: '#module(load="imudp")'
    #     line: 'module(load="imudp")'
    #     backup: yes
    #   when: ansible_connection == 'local'
