---
- hosts: all
  become: yes
  become_user: root
  tasks:
  
    - name: Start mysqld Service
      service:
        name: mysqld
        state: started
      when: inventory_hostname == "60160047-04"

    - name: Enable mysqld Service
      service:
        name: mysqld
        enabled: yes
      when: inventory_hostname == "60160047-04"