- hosts: all
  become: yes
  become_user: root
  vars:
    mysql_root_password: "123456"
  tasks:
    ################### Install Apache ###################

    # - name: Install mysql-server mariadb
    #   yum:
    #     name: "{{ packages }}"
    #     state: latest
    #   vars:
    #     packages:
    #       - mysql-server
    #       - mariadb-connector-c-config
    #       - mecab
    #       - mysql
    #       - mysql-common
    #       - mysql-errmsg
    #       - protobuf-lite
    #   when: "'dbServer' in group_names"

    - name: Install mariadb-server mariadb
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - mariadb-server
          - mariadb
          - python3-PyMySQL
      when: "'dbServer' in group_names"

    # - name: Start mysql Service
    #   service:
    #     name: mysqld
    #     state: started
    #     enabled: yes
    #   when: "'dbServer' in group_names"

    - name: Start mysql Service
      service:
        name: mariadb
        state: started
        enabled: yes
      when: "'dbServer' in group_names"

    - name: python -m pip install PyMySQL
      command: python -m pip install --upgrade pip
      when: "'dbServer' in group_names"

    - name: python -m pip install PyMySQL
      command: python -m pip install PyMySQL
      when: "'dbServer' in group_names"

    - name: Create a new database with name 'mydb'
      mysql_db:
        name: mydb
        state: present
      when: "'dbServer' in group_names"

    - name: Create database user with name 'myuser' and password '123456' with all database privileges
      mysql_user:
        name: "myuser"
        password: "123456"
        priv: "*.*:ALL,GRANT"
        host: "%"
        state: present
      when: "'dbServer' in group_names"

    # - name: Create a new database with name 'bobdata'
    #   mysql_db:
    #     name: test
    #     state: present
    #   when: "'dbServer' in group_names"

    # - name: Import DB
    #   shell: mysql test < /vagrant/ansible/sql/createtable2.sql
    #   when: "'dbServer' in group_names"

    - name: Copy database dump file
      copy:
        src: ./sql/createtable2.sql
        dest: /tmp
      when: "'dbServer' in group_names"

    - name: Restore database
      mysql_db:
        name: account
        state: import
        target: "/tmp/createtable2.sql"
      when: "'dbServer' in group_names"
    # - name: Restore database
    #   mysql_db:
    #     name: account
    #     state: import
    #     target: "/vagrant/ansible/sql/createtable2.sql"
    #   when: "'dbServer' in group_names"
