- hosts: all
  become: yes
  become_user: root
  tasks:
    ################### Install Apache ###################
    - name: Install python3
      yum:
        name: python3
        state: latest 
      when: "'dbServer' in group_names"

    - name: Install mariadb-server mariadb
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - mariadb-server
          - mariadb
      when: "'dbServer' in group_names"

    - name: Start mariadb Service
      service:
        name: mariadb
        state: started
        enabled: yes
      when: "'dbServer' in group_names"

    - name: Save the file and export the shares
      command: pip3 install MySQL-python
      when: "'dbServer' in group_names"
      
    - name: Make sure pymysql is present
      pip:
        name: pymysql
        state: present
      when: "'dbServer' in group_names"

    - name: Create database user with name 'bob' and password '12345' with all database privileges
      mysql_user:
        name: arnut
        password: 123456
        priv: '*.*:ALL'
        state: present
      when: "'dbServer' in group_names"
      
